name: Appium, Android and Allure
#This is the working version of the workflow for executing tests & generating allure reports with History
on:
  push:
    branches: [ github-actions ]

jobs:
  run-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 31 ]
        target: [ default ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 11
          distribution: 'adopt'

      - uses: actions/setup-node@v3.8.1
        with:
          node-version: '20.8.1'
      - run: |
          npm install -g appium
          appium -v
          appium driver install uiautomator2
          appium plugin install --source=npm appium-gestures-plugin
          appium &>/dev/null &
      ################################################################################
      #The part between the 2 lines is used for the creation ofr Cached emulator
      #This may save time when there is several tests to be executed or there is a need to close & open the emulator
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2.28.0
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          profile: Nexus 6
          arch: x86_64
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      ################################################################################
      - name: Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v2.28.0
        with:
          api-level: ${{ matrix.api-level }}
          #   force-avd-creation: false
          target: ${{ matrix.target }}
          profile: Nexus 6
          arch: x86_64
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: mvn clean test -Pgeneric -DconfigFilePath=configFiles/android.properties

      - name: Upload Allure reports
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ./target/allure-results

  generate-report:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure reports
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: ./allure-results

      - uses: actions/setup-node@v3.8.1
        with:
          node-version: '20.8.1'
      - run: |
          npm install -g allure-commandline --save-dev

      - name: Generate Allure report
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Publish Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history